### ISSUE TITLE
Adaptative damage

### ISSUE THREAD

**Issue by oDenis88** [IceReaper/Quake2Sharp#3]
As far I know, damage in QII is a fixed numeric value. Any idea on how to implement a way to calculate the damage based on the distance traveled by the projectile?

**Comment by IceReaper** [comment]
Should be easy to do tbh. But it depends on the weapon type.
Hitscan weapons already know the distance, so that information can be used directly. Other weapons might need some different logic.
But this is defenitely something doable by mods. Do not want to alter the core quake2 gameplay in this repository. Just modernize it.
